server:
  port: 3001
  
spring:
  application:
    name: feign  
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.126.140
    port: 5672
    username: root
    password: root       
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,  http://eureka2:2002/eureka

     
       
management:
  endpoints:
    web:
      exposure:
        include: "*"          

hystrix:
  metrics:
    enabled: true

feign:
  hystrix:
    enabled: true    